swagger: '2.0'
info:
  description:  胸痛ECG管理系统  
  version: 0.0.1
  title: 胸痛ECG管理系统  
  termsOfService: 'http:/swagger.io/terms/'
  contact:
    email: huxiaoyan@aecg.com.cn
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
host: localhost:3001
basePath: '/api'
tags:
  - name: 院前急救
    description: 1.胸痛ECG管理系统  
consumes:
  - application/json
produces:
  - application/json
  
schemes:
  - http
paths:
  /EcgReport/GetEcgReportList:
    get:
      tags:
      - "报告"
      summary: "获取报告列表"
      description: ""
      operationId: "GetEcgReportList"
      produces:
      - "application/json"
      parameters:
      - name: "begindate"
        in: "query"
        description: "开始时间"
        required: false
        type: "string"
      - name: "enddate"
        in: "query"
        description: "截止时间"
        required: false
        type: "string"
      - name: "keyword"
        in: "query"
        description: "搜索关键字"
        required: false
        type: "string"
      responses:
        200:
          description: '报告列表'
          schema:
            allOf:
              - properties:
                  Data:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          format: Int64
                          description: Id
                        sourceType:
                          type: integer
                          format: Int32
                          description: 数据来源
                        bindingInfo:
                          type: string
                          description: 绑定信息
                        repGuid:
                          type: string
                          description: 报告Guid
                        patName:
                          type: string
                          description: 病人姓名
                        patAge:
                          type: string
                          description: 病人年龄
                        patGender:
                          type: string
                          description: 病人性别
                        idCardNo:
                          type: string
                          description: 身份证号码
                        deviceCode:
                          type: string
                          description: 设备Code
                        deviceName:
                          type: string
                          description: 设备名称
                        examOrgId:
                          type: string
                          description: 检查机构Id
                        examOrgName:
                          type: string
                          description: 检查机构名称
                        applyOffice:
                          type: string
                          description: 申请科室
                        examTime:
                          type: string
                          format: date-time
                          description: 检查时间
                        examDrId:
                          type: string
                          description: 检查医生Id
                        examDrName:
                          type: string
                          description: 检查医生姓名
                        urgentType:
                          type: integer
                          description: 加急类型
                        urgentTime:
                          type: string
                          format: date-time
                          description: 加急时间
                        diagTime:
                          type: string
                          format: date-time
                          description: 诊断时间
                        diagOrgId:
                          type: string
                          description: 诊断机构Id
                        diagOrgName:
                          type: string
                          description: 诊断机构名称
                        diagDrId:
                          type: string
                          description: 诊断医生Id
                        diagDrName:
                          type: string
                          description: 诊断医生姓名
                        collectItemIndex:
                          type: integer
                          description: 医生诊断的是第几份图谱
                        collectItemIffsetMs:
                          type: integer
                          description: 医生诊断图谱的起始时间毫秒
                        collectItemBaseLine:
                          type: integer
                          description: 医生诊断图谱的基线
                        collectItemNotch:
                          type: integer
                          description: 医生诊断图谱的工频
                        collectItemLowPass:
                          type: integer
                          description: 医生诊断图谱的低通
                        flagSTEMI:
                          type: integer
                          description: STEMI诊断结果:阴性和阳性
                        repDiagnose:
                          type: string
                          description: 诊断结果
                        repDescription:
                          type: string
                          description: 诊断描述
                        repStatus:
                          type: integer
                          description: 报告状态
                        caseReportFormId:
                          type: integer
                          format: Int64
                          description: 胸痛档案Id
        400:
          description: Invalid Card
        403:
          description: Auth failed
  /EcgReport/GetNoRelatedDataList:
    get:
      tags:
      - "报告"
      summary: "获取报告关联列表"
      description: ""
      operationId: "GetNoRelatedDataList"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties: 
            noRelatedCondition:
              type: object
              $ref: '#/definitions/NoRelatedCondition'
      responses:
        200:
          description: '报告列表'
          schema:
            allOf:
              - properties:
                  Data:
                    type: object
                    properties:
                      List:
                        type: array
                        description: 检查项目结果列表
                        items:
                          properties:
                            Id:
                              type: integer
                              format: Int64
                              description: Id
                            SourceType:
                              type: integer
                              format: Int32
                              description: 数据来源
                            BindingInfo:
                              type: string
                              description: 绑定信息
                            RepGuid:
                              type: string
                              description: 报告Guid
                            PpatName:
                              type: string
                              description: 病人姓名
                            PatAge:
                              type: string
                              description: 病人年龄
                            PatGender:
                              type: string
                              description: 病人性别
                            IdCardNo:
                              type: string
                              description: 身份证号码
                            DeviceCode:
                              type: string
                              description: 设备Code
                            DeviceName:
                              type: string
                              description: 设备名称
                            ExamOrgId:
                              type: string
                              description: 检查机构Id
                            ExamOrgName:
                              type: string
                              description: 检查机构名称
                            ApplyOffice:
                              type: string
                              description: 申请科室
                            ExamTime:
                              type: string
                              format: date-time
                              description: 检查时间
                            ExamDrId:
                              type: string
                              description: 检查医生Id
                            ExamDrName:
                              type: string
                              description: 检查医生姓名
                            UrgentType:
                              type: integer
                              description: 加急类型
                            UrgentTime:
                              type: string
                              format: date-time
                              description: 加急时间
                            DiagTime:
                              type: string
                              format: date-time
                              description: 诊断时间
                            DiagOrgId:
                              type: string
                              description: 诊断机构Id
                            DiagOrgName:
                              type: string
                              description: 诊断机构名称
                            DiagDrId:
                              type: string
                              description: 诊断医生Id
                            DiagDrName:
                              type: string
                              description: 诊断医生姓名
                            CollectItemIndex:
                              type: integer
                              description: 医生诊断的是第几份图谱
                            CollectItemIffsetMs:
                              type: integer
                              description: 医生诊断图谱的起始时间毫秒
                            CollectItemBaseLine:
                              type: integer
                              description: 医生诊断图谱的基线
                            CollectItemNotch:
                              type: integer
                              description: 医生诊断图谱的工频
                            CollectItemLowPass:
                              type: integer
                              description: 医生诊断图谱的低通
                            FlagSTEMI:
                              type: integer
                              description: STEMI诊断结果:阴性和阳性
                            RepDiagnose:
                              type: string
                              description: 诊断结果
                            RepDescription:
                              type: string
                              description: 诊断描述
                            RepStatus:
                              type: integer
                              description: 报告状态
                            CaseReportFormId:
                              type: integer
                              format: Int64
                              description: 胸痛档案Id
                            ECGFile:
                              type: string
                              description: 上传心电图文件路径
                            CaseReportFormData:
                              type: object
                              description: 胸痛档案数据字典
                      PageIndex:
                        type: integer
                      PageSize:
                        type: integer
                      TotalCount:
                        type: integer
                      TotalPages:
                        type: integer
        400:
          description: Invalid Card
        403:
          description: Auth failed 
  /EcgReport/GetEcgReportDetail:
    post:
      tags:
      - "报告"
      summary: "请求报告波形详情"
      description: ""
      operationId: "GetEcgReportDetail"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties: 
            reportId:
              description: 报告ID
              type: string
            dpi:
              description: DPI 
              type: number
            width:
              description: 绘制的波形长度 
              type: number
            offset:
              description:  从哪开始绘制、绘制的偏移量 
              type: integer
            collectItemIndex:
              description:  波形的索引
              type: integer
            waveGain:
              description: 绘制的波形长度 
              type: integer
            waveSpeed:
              description: 绘制的波形长度 
              type: integer        
      responses:
        200:
          description: '报告详情'
          schema:
            allOf:
              - properties:
                  Data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: Int64
                        description: Id
                      sourceType:
                        type: integer
                        format: Int32
                        description: 数据来源
                      bindingInfo:
                        type: string
                        description: 绑定信息
                      repGuid:
                        type: string
                        description: 报告Guid
                      patName:
                        type: string
                        description: 病人姓名
                      patAge:
                        type: string
                        description: 病人年龄
                      patGender:
                        type: string
                        description: 病人性别
                      idCardNo:
                        type: string
                        description: 身份证号码
                      deviceCode:
                        type: string
                        description: 设备Code
                      deviceName:
                        type: string
                        description: 设备名称
                      examOrgId:
                        type: string
                        description: 检查机构Id
                      examOrgName:
                        type: string
                        description: 检查机构名称
                      applyOffice:
                        type: string
                        description: 申请科室
                      examTime:
                        type: string
                        format: date-time
                        description: 检查时间
                      examDrId:
                        type: string
                        description: 检查医生Id
                      examDrName:
                        type: string
                        description: 检查医生姓名
                      urgentType:
                        type: integer
                        description: 加急类型
                      urgentTime:
                        type: string
                        format: date-time
                        description: 加急时间
                      diagTime:
                        type: string
                        format: date-time
                        description: 诊断时间
                      diagOrgId:
                        type: string
                        description: 诊断机构Id
                      diagOrgName:
                        type: string
                        description: 诊断机构名称
                      diagDrId:
                        type: string
                        description: 诊断医生Id
                      diagDrName:
                        type: string
                        description: 诊断医生姓名
                      collectItemIndex:
                        type: integer
                        description: 医生诊断的是第几份图谱
                      collectItemIffsetMs:
                        type: integer
                        description: 医生诊断图谱的起始时间毫秒
                      collectItemBaseLine:
                        type: integer
                        description: 医生诊断图谱的基线
                      collectItemNotch:
                        type: integer
                        description: 医生诊断图谱的工频
                      collectItemLowPass:
                        type: integer
                        description: 医生诊断图谱的低通
                      flagSTEMI:
                        type: integer
                        description: STEMI诊断结果:阴性和阳性
                      repDiagnose:
                        type: string
                        description: 诊断结果
                      repDescription:
                        type: string
                        description: 诊断描述
                      repStatus:
                        type: integer
                        description: 报告状态
                      caseReportFormId:
                        type: integer
                        format: Int64
                        description: 胸痛档案Id
                      data:
                        type: object
                        description: 表单数据
                      waveforms:
                        type: object
                        $ref: '#/definitions/Waveforms'
        400:
          description: Invalid Card
        403:
          description: Auth failed 
          
     
definitions:
  WaveformsDto:
    type: "object"
    properties:
      shareInfo:
        type: array
        items:
         type: string
      currentShareIndex:
        type: integer
      waveForms:
        type: object
        $ref: '#/definitions/Waveforms'
  Waveforms:
    type: "object"
    properties:
      wavesStartTime:
        type: "string"
        description: ""
      waveformCollection:
        type: array
        items:
          $ref: '#/definitions/Waveform'
      viewParameter:
        type: object
        $ref: '#/definitions/ViewParameter'
  Waveform:
    type: "object"
    properties:
      type:
        type: "string"
        description: ""
      header:
        type: array
        items:
          type: "string"
      wave:
        type: array
        items:
          type: "string"
      headerWidth:
        type: "number"
        format: "double"
        description: ""
  ViewParameter:
    type: "object"
    properties:
      gridType:
        type: "integer"
        format: "int32"
        description: ""
      gain:
        type: "integer"
        format: "int32"
        description: ""
      speed:
        type: "integer"
        format: "int32"
        description: ""
      dPI:
        type: "number"
        format: "float"
        description: ""
  NoRelatedCondition: 
    type: "object"
    properties:
      PageIndex:
        description: 分页码
        type: number
      PageSize:
        description: 每一页条数 
        type: number
      IsRelated:
        description: 是否已关联
        type: boolean
      Keywords:
        description: 查询关键字 
        type: array
        items:
          type: "string"
