swagger: '2.0'
info:
  description: 事件管理 API
  version: 1.0.0
  title: 事件管理API
  termsOfService: 'http:/swagger.io/terms/'
  contact:
    email: sunming@aecg.com.cn
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
host: localhost:3001
basePath: '/OpenAPI'
tags:
  - name: Event
    description: 事件管理
consumes:
  - application/json
produces:
  - application/json

schemes:
  - http
paths:
  /Event/CreateEvent:
    post:
      tags:
        - Event
      summary: 创建事件
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              messageRequest:
                $ref: "#/definitions/EventParam"
      responses:
        200:
          description: 事件记录id
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: integer
                    description: 事件记录id

  /Event/GetEvent:
    post:
      tags:
        - Event
      summary: 获取事件信息
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: string
                description: 事件记录id
      responses:
        200:
          description: 事件信息
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    $ref: '#/definitions/EventInfoDTO'
  /Event/GetEventPager:
    post:
      tags:
        - Event
      summary: 获取事件记录列表
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              messageRequest:
                $ref: "#/definitions/EventPagerRequest"       
      responses:
        200:
          description: 事件信息
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    allOf:
                    - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Pagination'
                    properties:
                      List:
                        type: array
                        items:
                          $ref: '#/definitions/EventInfoDTO'                          

definitions:
  EventParam:
    type: object
    description: '胸痛事件入参DTO'
    properties:
      BId:
        type: string
        description: 事件业务的唯一号，时间采集器流水号、心电报告ID、手术记录ID、检查唯一号
      EventTime:
        type: string
        description: 事件时间
      EventType:
        type: string
        description: 事件类型
      Param:
        type: object
        description: 事件参数 键值对 对象Dictionary<string,string>

  EventInfoDTO:
    type: object
    description: '事件DTO'
    properties:
      Id:
        type: integer
        description: 事件记录id
      BId:
        type: string
        description: 事件业务的唯一号，时间采集器流水号、心电报告ID、手术记录ID、检查唯一号
      EventTime:
        type: integer
        description: 事件时间
      EId:
        type: string
        description: 事件唯一号
      EventType:
        type: string
        description: 事件类型
      Param:
        type: object
        description: 事件参数 键值对 对象Dictionary<string,string>

  EventPagerRequest:
    type: object
    description: '事件查询参数'
    properties:
      EventType:
        type: string
        description: 事件类型
      BId:
        type: string
        description: 事件业务的唯一号，时间采集器流水号、心电报告ID、手术记录ID、检查唯一号
      EventBeginTime:
        type: string
        description: 事件开始时间
      EventEndTime:
        type: string
        description: 事件结束时间
      PageIndex:
        type: integer
        description: 页数
      PageSize:
        type: integer
        description: 每页条数

