swagger: '2.0'
info:
  description: 这是一个消息推送对接业务 API
  version: 1.0.0
  title: 消息推送业务API
  termsOfService: 'http:/swagger.io/terms/'
  contact:
    email: huanghongshu@aecg.com.cn
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
host: localhost:3001
basePath: '/OpenAPI'
tags:
  - name: MessagePushConfig
    description: 消息推送配置对接业务
consumes:
  - application/json
produces:
  - application/json

schemes:
  - http
paths:
  /MessagePushConfig/GetMessagePushConfigList:
    post:
      tags:
        - MessagePushConfig
      summary: 获取消息推送配置列表
      responses:
        200:
          description: 消息推送配置列表
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    allOf:
                    - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Pagination'
                    properties:
                      List:
                        type: array
                        items:
                          $ref: '#/definitions/MessagePushConfig'
  /MessagePushConfig/GetMessagePushConfigDetail:
    post:
      tags:
        - MessagePushConfig
      summary: 获取推送配置
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              messageType:
                type: string
                description: 消息类型
      responses:
        200:
          description: 推送配置详情
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    $ref: '#/definitions/MessagePushConfigDetail'

  /MessagePushConfig/GetUser:
    post:
      tags:
        - MessagePushConfig
      summary: 获取用户信息
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              keyWord:
                type: string
                description: 关键字查询（用户名）
      responses:
        200:
          description: 用户信息
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    $ref: '#/definitions/UserInfo'

  /MessagePushConfig/GetNetWorkClock:
    post:
      tags:
        - MessagePushConfig
      summary: 获取网络时钟
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              keyWord:
                type: string
                description: 关键字查询（设备号）
      responses:
        200:
          description: 网络时钟信息
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    $ref: '#/definitions/NetWorkClockInfo'

  /MessagePushConfig/SaveMessagePushConfig:
    post:
      tags:
        - MessagePushConfig
      summary: 保存推送配置信息
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              messageRequest:
                $ref: "#/definitions/MessagePushConfigDetail"
      responses:
        200:
          description: 是否成功
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: boolean

  /MessagePushConfig/GetMessageType:
    post:
      tags:
        - MessagePushConfig
      summary: 获取推送类型下拉
      responses:
        200:
          description: 获取推送类型下拉响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: object
                    additionalProperties:
                      type: string

  /MessagePushConfig/GetMessageMode:
    post:
      tags:
        - MessagePushConfig
      summary: 获取推送模式下拉
      responses:
        200:
          description: 获取推送模式下拉响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: object
                    additionalProperties:
                      type: string

definitions:
  MessagePushConfig:
    type: object
    description: ''
    properties:
      MessageType:
        type: string
        description: 消息推送类型	  
      MessageTypeName:
        type: string
        description: 消息推送类型名称
      WeChatState:
        type: boolean
        description: 是否启用微信公众号
      NetWorkClockState:
        type: boolean
        description: 是否启用网络时钟
      SMSState:
        type: boolean
        description: 是否启用短信
      EmailState:
        type: boolean
        description: 是否启用邮件

  MessagePushConfigDetail:
    type: object
    description: '消息推送配置'
    properties:
      MessageType:
        type: string
        description: 消息推送类型	  
      MessageTypeName:
        type: string
        description: 消息推送类型名称
      WeChatState:
        type: boolean
        description: 是否启用微信公众号
      NetWorkClockState:
        type: boolean
        description: 是否启用网络时钟
      SMSState:
        type: boolean
        description: 是否启用短信
      EmailState:
        type: boolean
        description: 是否启用邮件
      UserTarget:
        type: array
        description: 人员推送目标
        items:
          $ref: '#/definitions/UserInfo'
      NetWorkClockTarget:
        type: array
        description: 网络时钟推送目标
        items:
          $ref: '#/definitions/NetWorkClockInfo'

  UserInfo:
    type: object
    description: '用户信息'
    properties:
      Id:
        type: integer
        description: 用户id
      RealName:
        type: string
        description: 用户真实姓名
      Mobile:
        type: string
        description: 手机号
      Email:
        type: string
        description: 邮箱
      IsBindMP:
        type: boolean
        description: 是否绑定微信公众号
      QRCodeUrl:
        type: string
        description: 微信MP二维码绑定地址

  NetWorkClockInfo:
    type: object
    description: '网络时钟信息'
    properties:
      Id:
        type: integer
        description: 主键
      Code:
        type: string
        description: 用户设备编号
      Name:
        type: string
        description: 设备类型

