swagger: '2.0'
info:
  description: 这是一个消息推送记录业务 API
  version: 1.0.0
  title: 消息推送记录业务API
  termsOfService: 'http:/swagger.io/terms/'
  contact:
    email: huanghongshu@aecg.com.cn
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
host: localhost:3001
basePath: '/OpenAPI'
tags:
  - name: MessagePushRecord
    description: 消息推送记录
consumes:
  - application/json
produces:
  - application/json

schemes:
  - http
paths:
  /MessagePushRecord/GetMessageRecordPager:
    post:
      tags:
        - MessagePushRecord
      summary: 消息推送记录列表
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              messageRequest:
                $ref: "#/definitions/MessageRequest"
      responses:
        200:
          description: 消息推送管理记录响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    allOf:
                    - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Pagination'
                    properties:
                      List:
                        type: array
                        items:
                          $ref: '#/definitions/MessagePushRecord'
  /MessagePushRecord/GetMessageRecordDetail:
    post:
      tags:
        - MessagePushRecord
      summary: 获取推送记录详情
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              messageType:
                type: integer
                description: 详情id
      responses:
        200:
          description: 推送记录详情
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    $ref: '#/definitions/MessagePushRecordDetail'
definitions:
  MessagePushRecord:
    type: object
    description: ''
    properties:
      Id:
        type: integer
        description: 主键
      MessageTypeName:
        type: string
        description: 消息推送类型名称
      MessageModeName:
        type: string
        description: 消息推送模式名称  
      Content:
        type: string
        description: 推送内容
      Result:
        type: string
        description: 推送结果
      PushTime:
        type: string
        description: 推送时间

  MessagePushRecordDetail:
    type: object
    description: ''
    properties:
      Id:
        type: integer
        description: 主键
      MessageTypeName:
        type: string
        description: 消息推送类型名称
      MessageModeName:
        type: string
        description: 消息推送模式名称  
      Content:
        type: string
        description: 推送内容
      Result:
        type: string
        description: 推送结果
      PushTime:
        type: string
        description: 推送时间
      WeChatMPTarget:
        type: string
        description: 微信公众号推送目标
      NetWorkClockTarget:
        type: string
        description: 网络时钟推送目标
      SMSTarget:
        type: string
        description: 短信推送目标
      EmailTarget:
        type: string
        description: 邮件推送目标

  MessageRequest:
    type: object
    description: ''
    properties:
      MessageType:
        type: string
        description: 消息推送类型Code
      MessageMode:
        type: string
        description: 消息推送模式Code
      PushTarget:
        type: string
        description: 消息推送目标(根据推送模式来定义、手机号、设备号等)
      BeginPushTime:
        type: string
        description: 开始时间
      EndPushTime:
        type: string
        description: 结束时间
      PageIndex:
        type: integer
        description: 表示第几页
      PageSize:
        type: integer
        description: 表示每页条数



