swagger: '2.0'
info:
  description: 胸痛档案日志 API
  version: 1.0.0
  title: Cppmas Web API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: zhangyun@aecg.com.cn
  license:
    name: Copyright
    url: 'http://www.aecg.com.cn'
host: 'www.aecg.com.cn:3009'
basePath: /OpenAPI
tags:
  - name: CaseReportForm
    description: 胸痛表单操作日志
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:

  /CaseReportForm/GetOperationLog:
    post:
      tags:
        - OperationLog
      summary: 操作日志
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: string
                description: 胸痛档案ID
      responses:
        '200':
          description: 操作日志列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: array
                    items:
                      $ref: '#/definitions/ArchiveOperationLog'

definitions:

  ArchiveOperationLog:
    type: object
    properties:
      Type:
        type: string
        description: 类型： 0：新增；1：更新
      Group:
        type: string
        description: 操作信息，没有就是显示表单
      Message:
        type: string
        description: 未知
      CreateName:
        type: string
        description: 操作时间
      CreateTime:
        type: string
        description: 创建时间
