swagger: '2.0'
info:
  description: 这是一个快检对接业务 API
  version: 1.0.0
  title: 快检设备API
  termsOfService: 'http:/swagger.io/terms/'
  contact:
    email: huanghongshu@aecg.com.cn
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
host: localhost:3001
basePath: '/OpenAPI'
tags:
  - name: POCT
    description: 快检设备对接业务
consumes:
  - application/json
produces:
  - application/json

schemes:
  - http
paths:
  /PointOfCareTesting/GetPOCTDevicePager:
    post:
      tags:
        - POCTDevice
      summary: 快检设备列表
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              pageIndex:
                type: integer
                description: 表示第几页
              pageSize:
                type: integer
                description: 每页条数
      responses:
        200:
          description: 快检设备列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    allOf:
                    - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Pagination'
                    properties:
                      List:
                        type: array
                        items:
                          $ref: '#/definitions/POCTDevice'

  /PointOfCareTesting/GetPOCTDevice:
    post:
      tags:
        - POCTDevice
      summary: 获取快检设备详情
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: integer
                description: 主键
      responses:
        200:
          description: 快检设备详情响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: object
                    items:
                      $ref: '#/definitions/POCTDevice'

  /PointOfCareTesting/UpdatePOCTDevice:
    post:
      tags:
        - POCTDevice
      summary: 更新快检设备
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              dto:
                $ref: "#/definitions/POCTDevice"
      responses:
        200:
          description: 修改快检设备响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: boolean

  /PointOfCareTesting/AddPOCTDevice:
    post:
      tags:
        - POCTDevice
      summary: 新增快检设备
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              dto:
                $ref: "#/definitions/POCTDevice"
      responses:
        200:
          description: 添加快检设备响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: integer

  /PointOfCareTesting/DeletePOCTDevices:
    post:
      tags:
        - POCTDevice
      summary: 删除快检设备(批量删除)
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              ids:
                type: array
                items:
                  type: integer
                description: 删除传入的数据Id
      responses:
        200:
          description: 删除快检设备响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: boolean

definitions:
  POCTDevice:
    type: object
    description: ''
    properties:
      Id:
        type: integer
        description: 主键
      Code:
        type: string
        description: 设备编号
      Name:
        type: string
        description: 设备名称
      TypeDicCode:
        type: string
        description: 设备类型编码
      TypeDicName:
        type: string
        description: 设备类型名称

