swagger: '2.0'
info:
  description: 这是一个快检对接业务 API
  version: 1.0.0
  title: 快检项目API
  termsOfService: 'http:/swagger.io/terms/'
  contact:
    email: huanghongshu@aecg.com.cn
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
host: localhost:3001
basePath: '/OpenAPI'
tags:
  - name: POCT
    description: 快检项目对接业务
consumes:
  - application/json
produces:
  - application/json

schemes:
  - http
paths:
  /PointOfCareTesting/GetPOCTItemPager:
    post:
      tags:
        - POCTItem
      summary: 快检项目列表
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              typeDicCode:
                type: string
                description: 设备类型
              pageIndex:
                type: integer
                description: 表示第几页
              pageSize:
                type: integer
                description: 每页条数
      responses:
        200:
          description: 快检项目列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    allOf:
                    - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Pagination'
                    properties:
                      List:
                        type: array
                        items:
                          $ref: '#/definitions/POCTItem'

  /PointOfCareTesting/GetPOCTItem:
    post:
      tags:
        - POCTItem
      summary: 获取快检项目详情
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: integer
                description: 主键
      responses:
        200:
          description: 快检项目详情响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: object
                    items:
                      $ref: '#/definitions/POCTItem'

  /PointOfCareTesting/UpdatePOCTItem:
    post:
      tags:
        - POCTItem
      summary: 更新快检项目
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              dto:
                $ref: "#/definitions/POCTItem"
      responses:
        200:
          description: 修改快检项目响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: boolean

  /PointOfCareTesting/AddPOCTItem:
    post:
      tags:
        - POCTItem
      summary: 新增快检项目
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              dto:
                $ref: "#/definitions/POCTItem"
      responses:
        200:
          description: 添加快检项目响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: integer

  /PointOfCareTesting/DeletePOCTItems:
    post:
      tags:
        - POCTItem
      summary: 删除快检项目(批量删除)
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              ids:
                type: array
                items:
                  type: integer
                  description: 删除传入的数据Id
      responses:
        200:
          description: 删除设备配置响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: boolean


definitions:
  POCTItem:
    type: object
    description: ''
    properties:
      Id:
        type: integer
        description: 主键
      Code:
        type: string
        description: 项目编码
      TypeDicCode:
        type: string
        description: 设备类型编码
      TypeDicName:
        type: string
        description: 设备类型名称
      AssistItemDicCode:
        type: string
        description: 辅助检查项编码
      AssistItemDicName:
        type: string
        description: 辅助检查项名称
      ValueRangeText:
        type: string
        description: 显示值范围
      ValueMin:
        type: string
        description: 显示值的最小值
      ValueMax:
        type: string
        description: 显示值的最大值
      NormalValueRangeText:
        type: string
        description: 正常值范围
      NormalValueMin:
        type: string
        description: 正常值的最小值
      NormalValueMax:
        type: string
        description: 正常值的最大值
      UnitDicCode:
        type: string
        description: 单位编码
      UnitDicName:
        type: string
        description: 单位名称
      Remark:
        type: string
        description: 备注

