swagger: '2.0'
info:
  description: 时间采集器 区域管理 API
  version: 1.0.0
  title: 时间采集器 Web API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: zhangyun@aecg.com.cn
  license:
    name: Copyright
    url: 'http://www.aecg.com.cn'
host: 'www.aecg.com.cn:3002'
basePath: /OpenAPI
tags:
  - name: TimeCollect
    description: 胸痛时间采集器业务
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:

  /Area/GetAreaPager:
    post:
      tags:
        - Area
      summary: 区域列表
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              queryArea:
                type: object
                properties:
                  Keyword:
                    type: string
                    description: 区域名称或房间名称
                  PageSize:
                    type: integer
                    description: 每页条数
                  PageIndex:
                    type: integer
                    description: 表示第几页
      responses:
        '200':
          description: 区域列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    allOf:
                      - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Pagination'
                    properties:
                      List:
                        type: array
                        items:
                          $ref: '#/definitions/Area'
  /Area/GetArea:
    post:
      tags:
        - Area
      summary: 查询区域
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: string
                description: 区域主键
      responses:
        '200':
          description: 区域查询响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: object
                    allOf:
                      - $ref: '#/definitions/Area'
                      - description: 区域

  /Area/AddArea:
    post:
      tags:
        - Area
      summary: 新增区域
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              area:
                type: object
                properties:
                  AreaName:
                    type: string
                    description: 区域名称
                  NearRoom:
                    type: array
                    description: 临近区域key列表
                    items:
                      type: string
                  IsRoom:
                    type: string
                    description: 区域是否为房间
                  KeyLocationType:
                    type: string
                    description: 关键点key
                  AreaDes:
                    type: string
                    description: 区域描述或备注
      responses:
        '200':
          description: 区域新增响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Area/UpdateArea:
    post:
      tags:
        - Area
      summary: 编辑区域
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              area:
                type: object
                properties:
                  Id:
                    type: string
                    description: 区域主键
                  AreaName:
                    type: string
                    description: 区域名称
                  NearRoom:
                    type: array
                    description: 临近区域key列表
                    items:
                      type: string
                  IsRoom:
                    type: string
                    description: 区域是否为房间
                  KeyLocationType:
                    type: string
                    description: 关键点key
                  AreaDes:
                    type: string
                    description: 区域描述或备注
      responses:
        '200':
          description: 区域编辑响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Area/DeleteArea:
    post:
      tags:
        - Area
      summary: 删除区域
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: string
                description: 区域主键
      responses:
        '200':
          description: 区域删除响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Area/GetKeyPonitType:
    post:
      tags:
        - Area
      summary: 关键点类型列表
      responses:
        '200':
          description: 关键点类型列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: array
                    items:
                      $ref: '#/definitions/KeyPonitType'


  /Area/GetRoomType:
    post:
      deprecated: true
      tags:
        - Area
      summary: 是否房间类型列表
      responses:
        '200':
          description: 是否房间类型列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: array
                    items:
                      $ref: '#/definitions/RoomType'


  /Area/GetNearRoom:
    post:
      tags:
        - Area
      summary: 临近区域列表
      responses:
        '200':
          description: 临近区域列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: array
                    items:
                      $ref: '#/definitions/NearRoom'

definitions:

  Area:
    type: object
    description: '区域返回列表对象'
    properties:
      Id:
        type: string
        description: 唯一标识Id
      AreaName:
        type: string
        description: 区域名称
      IsRoom:
        type: string
        description: 区域是否为房间
      NearRoom:
        type: array
        description: 临近区域key列表
        items:
          type: string
      KeyLocationType:
        type: string
        description: 关键点key
      KeyLocationName:
        type: string
        description: 关键点名称
      AreaDes:
        type: string
        description: 区域描述或备注

  KeyPonitType:
    type: object
    description: '关键点类型返回列表对象'
    properties:
      Id:
        type: string
        description: 唯一标识Id
      Name:
        type: string
        description: 类型名称

  RoomType:
    type: object
    description: '是否房间类型返回列表对象'
    properties:
      Id:
        type: string
        description: 唯一标识Id
      Name:
        type: string
        description: 是否房间名称

  NearRoom:
    type: object
    description: '临近区域列表对象'
    properties:
      Id:
        type: string
        description: 唯一标识Id
      Name:
        type: string
        description: 区域名称