swagger: '2.0'
info:
  description: 时间采集器 基站管理 API
  version: 1.0.0
  title: 时间采集器 Web API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: zhangyun@aecg.com.cn
  license:
    name: Copyright
    url: 'http://www.aecg.com.cn'
host: 'www.aecg.com.cn:3002'
basePath: /OpenAPI
tags:
  - name: TimeCollect
    description: 胸痛时间采集器业务
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /Anchor/GetAnchorPager:
    post:
      tags:
        - Anchor
      summary: 基站列表
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              queryAnchor:
                type: object
                properties:
                  Keyword:
                    type: string
                    description: 基站名称或基站名称
                  PageSize:
                    type: integer
                    description: 每页条数
                  PageIndex:
                    type: integer
                    description: 表示第几页
      responses:
        '200':
          description: 基站列表响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    allOf:
                      - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Pagination'
                      - properties:
                          List:
                            type: array
                            items:
                              $ref: '#/definitions/Anchor'

  /Anchor/GetAnchor:
    post:
      tags:
        - Anchor
      summary: 查询基站
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: string
                description: 基站主键
      responses:
        '200':
          description: 基站查询响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: object
                    allOf:
                      - $ref: '#/definitions/Anchor'
                      - description: 基站

  /Anchor/UpdateAnchor:
    post:
      tags:
        - Anchor
      summary: 编辑基站
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              anchor:
                type: object
                properties:
                  Id:
                    type: string
                    description: 基站主键
                  AnchorCode:
                    type: string
                    description: 基站编号
                  AnchorType:
                    type: string
                    description: 基站类型
                  IpAddress:
                    type: string
                    description: 基站ip
      responses:
        '200':
          description: 基站编辑响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Anchor/DeleteAnchor:
    post:
      deprecated: true
      tags:
        - Anchor
      summary: 删除基站
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                type: string
                description: 基站主键
      responses:
        '200':
          description: 基站删除响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Anchor/ImportConfigAnchor:
    post:
      tags:
        - Anchor
      summary: 导入配置基站
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          in: formData
          type: file
      responses:
        '200':
          description: 基站导入配置响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Anchor/ExportConfigAnchor:
    get:
      tags:
        - Anchor
      summary: 导出配置基站
      consumes:
        - application/json
      produces:
        - multipart/form-data
      responses:
        '200':
          description: 基站导出配置响应
          headers:
            Content-Disposition:
              description: Content-Disposition attachment;filename=filenamxx
              type: string
          schema:
            type: file

  /Anchor/OnLineTestAnchor:
    post:
      deprecated: true
      tags:
        - Anchor
      summary: 检测在线基站
      responses:
        '200':
          description: 检测在线基站响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Anchor/ConfigIssueAnchor:
    post:
      deprecated: true
      tags:
        - Anchor
      summary: 基站配置下发
      responses:
        '200':
          description: 基站配置下发响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: 返回的冗余数据，可以为空null

  /Anchor/UploadHospitalIchnography:
    post:
      tags:
        - Anchor
      summary: 上传医院平面图
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          in: formData
          type: file
      responses:
        '200':
          description: 上传医院平面图响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    $ref: '#/definitions/HospitalIchnography'

  /Anchor/DeleteHospitalIchnography:
    post:
      tags:
        - Anchor
      summary: 删除医院平面图
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              ichnographyUrl:
                type: string
                description: 医院平面图urlKey
      responses:
        '200':
          description: 删除医院平面图响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: string
                    description: null或数据

  /Anchor/GetHospitalIchnographyUrls:
    post:
      tags:
        - Anchor
      summary: 获取所有平面图的Id和Url
      responses:
        '200':
          description: 获取所有平面图的Id和Url响应
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: array
                    items:
                      $ref: '#/definitions/HospitalIchnography'

  /Anchor/GetEcgFileOfByte:
    get:
      tags:
        - Anchor
      summary: 获取平面图
      consumes:
        - application/json
      produces:
        - multipart/form-data
      parameters:
        - name: ichnographyUrl
          in: query
          description: 医院平面图获取url
      responses:
        '200':
          description: 获取平面图响应
          schema:
            type: file

definitions:

  Anchor:
    type: object
    description: '基站返回列表对象'
    properties:
      Id:
        type: string
        description: 唯一标识Id
      AnchorPositionId:
        type: string
        description: 定位点唯一标识Id
      AnchorPositionShortName:
        type: string
        description: 定位点简称
      AnchorCode:
        type: string
        description: 基站编号
      Status:
        type: string
        description: 基站在线状态
      AnchorType:
        type: string
        description: 基站类型
      IpAddress:
        type: string
        description: 基站ip

  HospitalIchnography:
    type: object
    description: '删除医院平面图响应对象'
    properties:
      Id:
        type: string
        description: 唯一标识Id
      IchnographyUrl:
        type: string
        description: 图片urikey

  AnchorType:
    type: object
    description: '基站类型响应对象'
    properties:
      Id:
        type: string
        description: 唯一标识Id
      Name:
        type: string
        description: 类型名称
