swagger: '2.0'
info:
  description: 时间屏程序接口规范，Rest风格
  version: 1.0.0
  title: 时间屏程序接口规范
  termsOfService: 'http://aecg.com.cn'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /timescreen
tags:
  - name: config
    description: 配置相关
schemes:
  - http
paths:
  /configs/{id}:
    get:
      tags:
        - config
      summary: 获取配置
      description: ''
      operationId: getConfig
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 设备ID
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ConfigsResponse'
        '403':
          description: Auth failed
  /uiprofile/{id}:
    get:
      tags:
        - config
      summary: 获取UI配置
      description: ''
      operationId: getUiProfile
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 设备ID
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/UiProfileResponse'
        '403':
          description: Auth failed
  /mediaset/{id}:
    get:
      tags:
        - config
      summary: 获取轮播图地址列表
      description: ''
      operationId: getMediaSet
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 设备ID
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MediaResponse'
        '403':
          description: Auth failed
definitions:
  ConfigsResponse:
    allOf:
      - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
      - type: object
        properties:
          data:
            type: array
            items:
              $ref: '#/definitions/Config'
  UiProfileResponse:
    allOf:
      - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
      - type: object
        properties:
          data:
            $ref: '#/definitions/UiProfile'
  MediaResponse:
    allOf:
      - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
      - type: object
        properties:
          data:
            type: array
            items:
              type: string
  Config:
    type: object
    description: 配置
    properties:
      key:
        type: string
        description: 配置Key
      value:
        type: string
        description: 配置Value
  UiProfile:
    type: object
    description: UI配置
    properties:
      frameMode:
        type: string
      bodyAppearance:
        $ref: '#/definitions/ContainerAppearance'
      dateAppearance:
        $ref: '#/definitions/TextAppearance'
      departmentAppearance:
        $ref: '#/definitions/TextAppearance'
      clockAppearance:
        $ref: '#/definitions/TextAppearance'
      noticeAppearance:
        $ref: '#/definitions/TextAppearance'
      warningAppearance:
        $ref: '#/definitions/TextAppearance'
      marqueeAppearance:
        $ref: '#/definitions/TextAppearance'
  ContainerAppearance:
    type: object
    description: 容器样式
    properties:
      backgroundColor:
        type: string
      backgroundImage:
        type: string
  TextAppearance:
    type: object
    properties:
      color: 
        type: string
      fontSize:
        type: integer
        format: int32
      fontFace:
        type: string
      backgroundColor:
        type: string
      align:
        type: string
      height: 
        type: integer
