swagger: '2.0'
info:
  description: 心电云平台医生 API
  version: 1.0.0
  title: 心电云平台医生 API
  termsOfService: 'http://aecg.com.cn'
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
basePath: /v1
tags:
  - name: Doctor
    description: 医生信息相关
paths:
  /doctors-in-exmaination-group:
    get:
      tags:
        - examination
      summary: 获取检查医生列表
      description: ''
      operationId: findDoctorsInExaminationGroup
      parameters:
        - name: X-Access-Token
          in: header
          description: 鉴权token
          required: true
          type: string
      responses:
        '200':
          description: 获取诊断医生列表成功
          schema:
            $ref: '#/definitions/DoctorsResponse'

  /doctors-in-diagnosis-group:
    get:
      tags:
        - diagnose
      summary: 获取诊断医生列表
      description: ''
      operationId: findDoctorsInDiagnosisGroup
      parameters:
        - name: X-Access-Token
          in: header
          description: 鉴权token
          required: true
          type: string
      responses:
        '200':
          description: 获取诊断医生列表成功
          schema:
            $ref: '#/definitions/DoctorsResponse'

definitions:
  DoctorsResponse:
    allOf:
      - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Response'
      - type: object
        properties:
          data:
            type: array
            items:
              $ref: '#/definitions/Doctor'
  Doctor:
    type: object
    description: 医生
    properties:
      id:
        type: string
        description: 医生ID
      name:
        type: string
        description: 医生姓名
      permission:
        type: array
        description: 权限列表
        items:
          type: string
