swagger: '2.0'
info:
  description: 心电云平台心电图档案数据 API
  version: 1.0.0
  title: ECG File Archives API
  termsOfService: 'http:/swagger.io/terms/'
  contact:
    email: xuwei@aecg.com.cn
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
host: localhost:3001
basePath: '/api'
tags:
  - name: ECG
    description: 心电图
consumes:
  - application/json
produces:
  - application/json

schemes:
- http
- https

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization

paths:
  /ecg-archives/{id}/waveform:
    get:
      tags:
        - ECG
      summary: 获取心电图图谱波形
      description: 获取心电数据指定的图谱的波形
      operationId: getEcgFileAtalsWaveform
      parameters:
        - name: id
          in: path
          description: 获取心电图波形数据
          type: integer
          format: int64
          required: true
        - name: atlasIndex
          in: path
          description: 图谱索引
          type: integer
          format: int32
          required: true
        - name: sampleRate
          in: query
          description: 采样率(Hz)
          required: true
          type: integer
          format: int32
        - name: gain
          in: query
          type: integer
          format: int32
          description: 增益，默认值为 10 (10mm/mV)
          required: true
        - name: pace
          in: query
          type: integer
          format: int32
          description: 走速，默认值为 25 (25mm/s)
          required: true
        - name: duration
          in: query
          type: integer
          format: int32
          description: 长度(毫秒)
          required: true
        - name: offset
          in: query
          type: integer
          format: int32
          description: 偏移量, 单位是毫秒，默认值为 0

      responses:
        '200':
          description: 数组形式返回多个导联的波形数据
          schema:
            $ref: '#/definitions/EcgResponse'

  /ecg-archives:
    post:
      tags:
        - ECG
      operationId: uploadEcgArchives
      description: 上传心电图数据
      consumes:
       - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          description: 要上传的心电图文件
      responses:
        '200':
          description: 数组形式返回多个导联的波形数据
          schema:
            type: object
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Response'

definitions:
  EcgResponse:
    allOf:
    - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Response'
    - properties:
        data:
          type: object
          properties:
            atlas:
              description: 图谱数据
              type: object
              $ref: '#/definitions/Atlas'
            waveforms:
              description: 波形数据
              type: array
              items:
                $ref: '#/definitions/Waveform'
  Atlas:
    type: object
    description: 图谱采集开始时间
    properties:
      startTime:
        type: string
        format: date
        description: 图谱采集开始时间
      totalDuration:
        type: integer
        format: int32
        description: 时间总长度，单位为毫秒(ms)
  Waveform:
    description: 波形数据
    type: object
    properties:
      type: 
        type: integer
        format: int32
        description: 导联头类型
      wave:
        type: array
        items:
          type: number
          format: float
          description: 波形
          
        

