swagger: '2.0'
info:
  description: 心电采集程序接口规范，Rest风格
  version: 1.0.0
  title: 心阅诊断程序接口规范
  termsOfService: 'http://aecg.com.cn'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /diagnose
schemes:
  - http
paths:
  /Diaglexicon/CheckLexiconVersion:
    get:
      tags:
        - CheckLexiconVersion
      summary: 较验词库版本
      description: ''
      operationId: CheckLexiconVersion
      produces:
        - application/json
      parameters:
        - name: token
          in: path
          description: 鉴权token
          required: true
          type: string
        - in: path
          name: versionCode
          description: 版本号
          required: true
          type: string
      responses:
        200:
          description: '较验词库版本'
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: boolean
                    
  /Diaglexicon/GetLexicons:
    get:
      tags:
        - GetLexicons
      summary: 获取机构词库列表
      description: ''
      operationId: GetLexicons
      produces:
        - application/json
      parameters:
        - name: token
          in: path
          description: 鉴权token
          required: true
          type: string
        - in: path
          name: versionCode
          description: 版本号
          required: true
          type: string
      responses:
        200:
          description: '较验词库版本'
          schema:
            allOf:
              - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/ClassicResponse'
              - properties:
                  Data:
                    type: array
                    items: 
                      type: object
                      $ref: "#/definitions/OrgLexiconDto"


definitions:
  OrgLexiconDto: 
    type: object
    description: 词库信息
    properties:
      Id:
        type: string
        description: 标识
      Content:
        type: string
        description: 词汇
      ChildContentList:
        type: array
        items:
          type: object
          properties:
            ChildId:
              type: string
              description: 下级词汇标识
            ChildContent: 
              type: string
              description: 下级词汇内容