swagger: '2.0'
info:
  description: 心电云平台病人API
  version: 1.0.0
  title: 心电采集程序接口规范
  termsOfService: 'http://aecg.com.cn'
  license:
    name: Copyright
    url: 'http:/www.aecg.com.cn'
basePath: /v1/acquisitor
tags:
  - name: Patient
consumes:
  - application/json
produces:
  - application/json
paths:
  /patients:
    get:
      tags:
        - Patient
      summary: 获取病人信息
      description: ''
      operationId: getPatient
      parameters:
        - name: X-Access-Token
          in: header
          description: 鉴权token
          required: true
          type: string
        - name: cardType
          in: query
          description: 卡号类型
          required: true
          type: string
        - name: cardNo
          in: query
          description: 卡号
          required: true
          type: string
      responses:
        '200':
          description: 获取病人信息成功
          schema:
            $ref: '#/definitions/PatientResponse'

definitions:
  PatientResponse:
    allOf:
      - $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/Response'
      - type: object
        properties:
          data:
            type: object
            properties:
              patient:
                $ref: '#/definitions/Patient'
              clinical:
                $ref: '#/definitions/Clinical'
  Card:
    type: object
    description: 卡号/证件号信息
    properties:
      key:
        type: string
        description: 卡/证件类型
      value:
        type: string
        description: 卡/证件号

  Patient:
    type: object
    description: 患者信息
    properties:
      name:
        type: string
        description: 患者姓名
      gender:
        $ref: 'http://apispec.aecg.com.cn/schemas/common.yaml#/definitions/gender'
      age:
        type: string
        description: 患者年龄
      cards:
        type: array
        description: 卡号/证件号
        items:
          $ref: '#/definitions/Card'
      contact:
        type: string
        description: 患者联系方式（电话）

  Clinical:
    type: object
    description: 临床信息
    properties:
      ward:
        type: string
        description: 病区
      bed:
        type: string
        description: 床号
