swagger: '2.0'
info:
  description: GG API Repository
  version: 1.0.0
  title: Basic API
  contact:
    email: zmingg@outlook.com
host: zmingg.com
basePath: /v1
tags:
- name: Auth
  description: 认证
- name: Passport
  description: 账号
- name: Article
  description: 文章
consumes:
- application/json
produces:
- application/json
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
paths:
  /auth:
    post:
      tags:
      - Auth
      summary: 创建认证（登陆）
      operationId: createAuth
      parameters:
      - in: body
        name: body
        description: 认证信息
        required: true
        schema:
          $ref: '#/definitions/PassportAuth'
      responses:
        '200':
          description: 登陆成功
          schema:
            $ref: '#/definitions/AuthCreationResponse'

  /passports:
    get:
      tags:
      - Passport
      summary: 获取通行证列表
      operationId: findPassports
      security:
      - ApiKeyAuth: []
      parameters:
      - name: pageIndex
        in: query
        description: 当前页码
        required: true
        type: integer
        format: int32
      - name: pageSize
        in: query
        description: 分页尺寸
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: 登陆成功
          schema:
            $ref: '#/definitions/AuthCreationResponse'


definitions:

  AuthCreationResponse:
    allOf:
    - $ref: '#/definitions/Response'
    - type: object
      properties:
        data:
          $ref: '#/definitions/AuthVO'

  AuthVO:
    type: object
    properties:
      token:
        type: string
      passport:
        $ref: '#/definitions/PassportUser'

  Passport:
    allOf:
    - $ref: '#/definitions/PassportAuth'
    - $ref: '#/definitions/PassportUser'

  PassportUser:
    type: object
    properties:
      id:
        type: integer
        format: int32
      nickname:
        type: string
      status:
        type: integer
        format: int32
        enum:
        - 0
        - 1
        description: >
          * 0 - 停用
          * 1 - 启用
      email:
        type: string
      remark:
        type: string

  PassportAuth:
    type: object
    properties:
      username:
        type: string
      password:
        type: string

# 通用响应出口
  Response:
    type: object
    properties:
      code:
        type: integer
        format: int32
        description: 响应代码
      msg:
        type: string
        description: 响应信息
      serverTime:
        type: integer
        description: 响应时间

  BooleanResponse:
    allOf:
    - $ref: '#/definitions/Response'
    - type: object
      properties:
        data:
          type: boolean